### ISSUE TITLE
need help whit packaging for linux?

### ISSUE THREAD

**Issue by Josakko** [v-pun215/eClient#2]
i see that you dont have support for linux so need help whit packaging for linux?

**Comment by v-pun215** [comment]
Yeah would be epic!

**Comment by v-pun215** [comment]
Sorry for replying late :(

**Comment by Josakko** [comment]
you got discord?

**Comment by Josakko** [comment]
if you have just add me its "josakko"

**Comment by v-pun215** [comment]
nah man you got zoom or smth? zoom works by sending invites (for chats) by emails (mines vihaan.pundir26@gmail.com)

**Comment by Josakko** [comment]
maybe telegram, signal, anything?

**Comment by Josakko** [comment]
if you dont just send me zoom invite on josakko2358@gmail.com

**Comment by v-pun215** [comment]
sent bro
