### ISSUE TITLE
ЕБЛАН НАХУЙ ТЫ ЗАСУНУЛ ВЕСЬ КОД В main.py

### ISSUE THREAD

**Issue by Sesdear** [v-pun215/eClient#4]
YOU KUKAN

**Comment by v-pun215** [comment]
Im working on the latest release. The latest release will have many bug fixes. This will also fix the bug you are experiencing. Please wait patiently cuz I'm the only one working on this project. Also, please don't swear in Issues. It is agains the GitHub Community Guidelines. Also, please write in English, as I do not speak Russian.
